### ISSUE TITLE
Failed to activate the coverage-gutter package

### ISSUE THREAD

**Issue by aniss** [gskachkov/tstatompackage#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.205.0
**System**: Mac OS X 10.10.2
**Thrown From**: [coverage-gutter](https://github.com/gskachkov/tstatompackage) package, v0.12.0
### Stack Trace

Failed to activate the coverage-gutter package

```
At The `::subscribe` method is no longer available on SpacePen views.

To store multiple subscription objects for later disposal, add them to a
`CompositeDisposable` instance (https://atom.io/docs/api/v0.150.0/CompositeDisposable)
and call `.dispose()` on it explicitly in this view's `::detached` hook.

Error: The `::subscribe` method is no longer available on SpacePen views.

To store multiple subscription objects for later disposal, add them to a
`CompositeDisposable` instance (https://atom.io/docs/api/v0.150.0/CompositeDisposable)
and call `.dispose()` on it explicitly in this view's `::detached` hook.
  at CoverageView.View.subscribe (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:576:11)
  at CoverageView.module.exports.CoverageView.initialize (/Users/admin/.atom/packages/coverage-gutter/lib/coverage-view.coffee:34:6)
  at CoverageView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new CoverageView (/Users/admin/.atom/packages/coverage-gutter/lib/coverage-view.coffee:8:3)
  at /Users/admin/.atom/packages/coverage-gutter/lib/main.coffee:13:12
  at Array.forEach (native)
  at Object.module.exports.activate (/Users/admin/.atom/packages/coverage-gutter/lib/main.coffee:12:38)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:770:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:06.1.0 nuclide-click-to-symbol:activate (atom-text-editor.editor.is-focused)
     -0:05.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 testcoverage:show (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-htmlhint",
      "nuclide-file-tree"
    ]
  },
  "coverage-gutter": {
    "pathToLCOV": "/var/www/availability/ui/test/coverage/lcov.info"
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.6.3
coverage-gutter, v0.12.0
docblockr, v0.7.2
linter, v0.12.6
linter-eslint, v0.5.8
nuclide-click-to-symbol, v0.0.0
nuclide-code-format, v0.0.0
nuclide-diff-view, v0.0.0
nuclide-flow, v0.0.0
nuclide-hack, v0.0.0
nuclide-hg-repository, v0.0.0
nuclide-remote-projects, v0.0.0
nuclide-ssh-dialog, v0.0.0
nuclide-tabs, v0.0.0
nuclide-type-hint, v0.0.0
react, v0.12.0
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by gskachkov** [comment]
Thanks for the reporting.
Ohhh, something new in Atom. I'll take a look soon this issue.

**Comment by gskachkov** [comment]
Fixed

**Comment by agosto-levitomes** [comment]
I am still getting (I believe) the above error.

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [coverage-gutter](https://github.com/gskachkov/tstatompackage) package, v0.19.0

### Stack Trace

Failed to activate the coverage-gutter package

```
At EISDIR: illegal operation on a directory, read

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.fs.readFileSync (fs.js:438:24)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at CoverageView.module.exports.CoverageView.getCoverage (/Users/levi/.atom/packages/coverage-gutter/lib/coverage-view.coffee:56:18)
    at CoverageView.module.exports.CoverageView.showCoverage (/Users/levi/.atom/packages/coverage-gutter/lib/coverage-view.coffee:51:22)
    at CoverageView.module.exports.CoverageView.initialize (/Users/levi/.atom/packages/coverage-gutter/lib/coverage-view.coffee:45:6)
    at CoverageView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new CoverageView (/Users/levi/.atom/packages/coverage-gutter/lib/coverage-view.coffee:9:3)
    at /Users/levi/.atom/packages/coverage-gutter/lib/main.coffee:13:12
    at Array.forEach (native)
    at Object.module.exports.activate (/Users/levi/.atom/packages/coverage-gutter/lib/main.coffee:12:38)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:801:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:00.7.0 testcoverage:show (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "projectHome": "/Users/levi/projects"
  },
  "coverage-gutter": {
    "basePath": "/Users/levi/projects/agosto/contentmanager",
    "pathToLCOV": "/Users/levi/projects/agosto/contentmanager/coverage/ui/PhantomJS 1.9.8 (Mac OS X 0.0.0)"
  }
}
```

### Installed Packages

``` coffee
# User
coverage-gutter, v0.19.0
git-log, v0.4.1
linter, v1.11.3
linter-jscs, v3.4.1

# Dev
No dev packages
```
